### PR TITLE
Some changes to your project.

### PR DESCRIPTION
**Pull request by nm17**

### CODE REVIEW

**Comment by runfalk** [comment]
Hi @NeverMine17,

I appreciate your contribution. I didn't intend for anyone to find this until I properly added a `README` and a `LICENSE`. How did you find this?

## Regarding the actual PR:
I'm unsure how CMake benefits this toy project. The Makefile is 5 LOC while the CMake files har 50 LOC and they are error prone since new files manually have to be added, while the current solution automatically discovers new files. Which particular use case did you want to solve?

I'm not sure how I feel about arbitrarily changing the code style to match the Linux kernel. While standards are important I'm not sure that's the coding style of my choice.

**Comment by nm17** [comment]
I just find a random project to contribute to that was created on the day I contributed.
About CMake - i just think that its a lot more readable than the Makefile, but I guess you right.
Waiting for your comments on this!

**Comment by runfalk** [comment]
Hi @NeverMine17,

I'll not merge the CMake addition, since it only complicates the development process as of now. Maybe time will change that if the project grows.

I'll not merge the code-style changes either since there are no obvious benefits to that one. I may revisit changing code style again later.

If you redo the merge request I can and will merge the `README`.

None of my decisions are set in stone. If you can argue for a particular change I'm willing to change my opinion.

**Comment by nm17** [comment]
> If you redo the merge request I can and will merge the README.

Just cherrypick it.

**Pull request closed without merging**
